# Generated by Django 3.2.15 on 2022-10-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_text',
        ),
    ]
